
{{- range $current_secret_name, $current_secret := .Values.certIssuer.extraSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $current_secret_name }}
  namespace: cert-manager
type: Opaque
data:
{{- range $key, $value := $current_secret }}
  {{ $key }}:  {{ print $value | b64enc | quote -}}
{{- end }}
{{- end }}